AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Description: The environment to which the subnets belong to
    Type: String
    AllowedValues:
      - dev
      - stage
      - prod
    ConstraintDescription: Must be valid environment name
  VPCID:
    Description: AWS Provided VPC Identifier
    Type: 'AWS::EC2::VPC::Id'
  PublicSubnetID:
    Description: The public subnet in which NAT gateway has to be created
    Type: 'AWS::EC2::Subnet::Id'
  NATGatewayName:
    Description: Name of the NAT gateway
    Type: String
Resources:
  NATGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt 
        - NATElasticIP
        - AllocationId
      SubnetId: !Ref PublicSubnetID
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Ref NATGatewayName
  NATElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
  NATRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPCID
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Ref NATGatewayName
  Route:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref NATRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway
Outputs:
  NATGatewayID:
    Description: NATGatewayID
    Value: !Ref NATGateway
  NATGatewayElasticIP:
    Description: NATGateway's Elastic IP
    Value: !Ref NATElasticIP
  NATGatewayRouteTableID:
    Description: RouteTableId of NAT Gateway
    Value: !Ref NATRouteTable
